name: Pipeline de IC

on:
  push:
    branches: [ "main", "master", "feature/*" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Obtener el codigo fuente
      uses: actions/checkout@v3

    - name: Configurar entorno Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Extraer numero de tarjeta de Trello
      id: extraer_tarjeta
      run: |
        # 1. Juntamos el nombre de la rama y los últimos 10 commits para buscar ahí
        TEXTO_BUSQUEDA="${{ github.ref_name }} $(git log -10 --oneline)"
        
        
        # ignora mayusculas, guiones o espacios entre tarjeta y el número
        NUMERO=$(echo "$TEXTO_BUSQUEDA" | grep -oPi 'tarjeta[- ]?\K\d+' | head -n 1 || echo "")
        
        # Si no encuentra esa palabra, busca cualquier número aislado en los últimos commits
        if [ -z "$NUMERO" ]; then
          NUMERO=$(echo "$TEXTO_BUSQUEDA" | grep -oP '\b\d+\b' | head -n 1 || echo "")
        fi

        # Si está vacío, el pipeline SE ROMPE y avisa el motivo
        if [ -z "$NUMERO" ]; then
          echo "ERROR nombrar con tarjeta(<numero>) en tus commits."
          exit 1
        fi

        echo "El número de tarjeta detectado es: $NUMERO"
        echo "trello_card_num=$NUMERO" >> $GITHUB_OUTPUT

    - name: Mover tarjeta en Trello a EN PROGRESO
      run: |
        # 1. Buscamos el ID real de la tarjeta en el tablero usando su número secuencial (idShort)
        CARD_ID=$(curl -s "https://api.trello.com/1/boards/6a207672ad34d75b8b66142b/cards?key=${{ secrets.TRELLO_API_KEY }}&token=${{ secrets.TRELLO_TOKEN }}" | jq -r ".[] | select(.idShort == ${{ steps.extraer_tarjeta.outputs.trello_card_num }}) | .id")
        echo "ID real de la tarjeta encontrado: $CARD_ID"
        
        # 2. La movemos a la lista de En Progreso (terminada en 1482)
        curl -s -X PUT -d "idList=6a207672ad34d75b8b661482" "https://api.trello.com/1/cards/$CARD_ID?key=${{ secrets.TRELLO_API_KEY }}&token=${{ secrets.TRELLO_TOKEN }}"

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Revisar estilo de codigo (Linteo con Flake8)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 

    - name: Ejecutar pruebas unitarias
      run: |
        python -m unittest test_app.py

    - name: Mover tarjeta en Trello a LISTO
      if: success() && (github.ref_name == 'main' || github.ref_name == 'master')
      run: |
        # 1. Buscamos el ID real de la tarjeta usando su número secuencial
        CARD_ID=$(curl -s "https://api.trello.com/1/boards/6a207672ad34d75b8b66142b/cards?key=${{ secrets.TRELLO_API_KEY }}&token=${{ secrets.TRELLO_TOKEN }}" | jq -r ".[] | select(.idShort == ${{ steps.extraer_tarjeta.outputs.trello_card_num }}) | .id")
        
        # 2. La movemos a la lista de Listo
        curl -s -X PUT -d "idList=6a207672ad34d75b8b661483" "https://api.trello.com/1/cards/$CARD_ID?key=${{ secrets.TRELLO_API_KEY }}&token=${{ secrets.TRELLO_TOKEN }}"