name: Pipeline de IC

on:
  push:
    branches: [ "main", "master", "feature/*" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Obtener el codigo fuente
      uses: actions/checkout@v3

    - name: Configurar entorno Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Extraer numero de la tarjeta de Trello

    - name: Extraer numero de tarjeta de Trello
      id: extraer_tarjeta
      run: |
        RAMA="${{ github.ref_name }}"
        NUMERO=$(echo "$RAMA" | grep -oP 'tarjeta-\K\d+')
        echo "El número de tarjeta detectado es: $NUMERO"
        echo "trello_card_num=$NUMERO" >> $GITHUB_OUTPUT
    
      #Pasa de "para hacer" a "en progreso" al iniciar el pipeline
    - name: Mover tarjeta en Trello a EN PROGRESO
      uses: nate-stacy/trello-action@v1.0.0
      with:
        trello-api-key: ${{ secrets.TRELLO_API_KEY }}
        trello-token: ${{ secrets.TRELLO_TOKEN }}
        trello-board-id: 'ZOn3bWSz' # El id del board de Trello
        trello-list-id: '6a207672ad34d75b8b661482' 
        trello-card-id: ${{ steps.extraer_tarjeta.outputs.trello_card_num }}

    #CONTROL DE CALIDAD Y PRUEBAS

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Revisar estilo de codigo (Linteo con Flake8)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Ejecutar pruebas unitarias
      run: |
        python -m unittest test_app.py

    #Mover a "Listo" cuando el pipeline se ejecute correctamente

    - name: Mover tarjeta en Trello a LISTO
      if: success()
      uses: nate-stacy/trello-action@v1.0.0
      with:
        trello-api-key: ${{ secrets.TRELLO_API_KEY }}
        trello-token: ${{ secrets.TRELLO_TOKEN }}
        trello-board-id: 'ZOn3bWSz' # El id del board de Trello 
        trello-list-id: '6a207672ad34d75b8b661483'    
        trello-card-id: ${{ steps.extraer_tarjeta.outputs.trello_card_num }}